#pragma once

constexpr u32 CHUNK_WIDTH = 16;
constexpr u32 SUBCHUNK_SIZE = CHUNK_WIDTH;
constexpr u32 SUBCHUNK_VOLUME = SUBCHUNK_SIZE * SUBCHUNK_SIZE * SUBCHUNK_SIZE;
constexpr u32 SUBCHUNK_COUNT = 12;
constexpr u32 CHUNK_HEIGHT = SUBCHUNK_COUNT * SUBCHUNK_SIZE;
